FROM kalilinux/kali-rolling

RUN apt update && apt install -y \
    curl \
    iputils-ping \
    nano \
    iproute2 \
    net-tools \
    dnsutils \
    wget \
    traceroute \
    john \
    sudo \
    hashcat \
    openssh-server \
    nmap \
    hydra \
    tcpdump \
    && apt clean
